name: Build snake game and deploy to github pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    name: Build and deploy pygame
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout
      run: |
            echo "Attempting to install pygbag"
            python -m pip install pygbag pygame
            echo "Successfully installed pygbag"
            echo "Attempting to build the game"
            python -m pygbag --build $GITHUB_WORKSPACE/game.py
            echo "Successfully build the game and complied to WebAssembly"

    - name : "Upload to GitHub pages branch gh-pages"
      uses: JamesIves/github-pages-deploy-action@4.7.2
      with:
        branch: gh-pages
        folder: build/web
